spring.application.name=SmartStock


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartstock
spring.datasource.username=postgres
spring.datasource.password=159811

# JPA/Hibernate Configuration
# Use "update" for development to persist data across restarts.
# Hibernate will try to alter the schema to match entities without dropping data.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.key=aVeryLongAndSuperSecureSecretKeyForMySmartStockApplication2025!@#$